"""Configuration for the rebuilt virtual-pick strike task."""
from __future__ import annotations

from pathlib import Path

from tab2body.song_bundles import strike_goal_path

PACKAGE_ROOT = Path(__file__).resolve().parent
PROJECT_ROOT = PACKAGE_ROOT.parent
DEFAULT_STRIKE_SONG_ID = "00_SS1-68-E_comp"
DEFAULT_BUNDLE = strike_goal_path(DEFAULT_STRIKE_SONG_ID)


STRIKE = {
    "observation_contract": "strike.observation.v2",
    "goal_path": str(DEFAULT_BUNDLE),
    "grip_reference_path": str(
        PROJECT_ROOT / "strike" / "02_physical_control"
        / "pick-grip-reference.json"
    ),
    "num_envs": 512,
    "device": "cuda:0",
    "seed": 42,
    "iterations": 50000,
    "action_scale": 1.0,
    "action_alpha": 0.5,
    "reset_noise": 0.0,
    "reset_soft_limit_fraction": 0.02,
    "policy_init_std": 0.04,
    "failure_termination_penalty": -10.0,
    "grip_control": {
        "pinch_residual_rad": 0.08,
        "free_residual_rad": 0.22,
        "bad_quality_threshold": 0.85,
    },
    "zone": {
        "allowed_y_min_m": -0.385,
        "allowed_y_max_m": -0.255,
        "preferred_y_min_m": -0.355,
        "preferred_y_max_m": -0.295,
        "phrase_lane_y_m": -0.325,
        "lane_core_half_width_m": 0.006,
        "lane_allowed_half_width_m": 0.0125,
    },
    "trajectory": {
        "ready_across_offset_m": 0.003,
        "entry_across_offset_m": 0.0015,
        "exit_across_offset_m": 0.003,
        "ready_height_m": 0.008,
        "crossing_depth_m": 0.0015,
        "ready_distance_m": 0.010,
        "entry_distance_m": 0.006,
        "ready_hold_frames": 6,
        "recovery_frames": 12,
        "follow_through_min_frames": 1,
        "approach_lead_s": 0.25,
        "clearance_height_m": 0.010,
        "clearance_distance_m": 0.004,
    },
    "detector": {
        "min_depth_m": 0.001,
        "min_across_speed_m_s": 0.05,
        "parallel_epsilon": 1e-9,
        "min_displacement_m": 1e-5,
        "rearm_distance_m": 0.003,
        "rearm_min_frames": 2,
    },
    "safety": {
        "penetration_threshold_m": 0.005,
        "penetration_frames": 3,
        "penetration_termination": False,
    },
    "wrong_crossing_termination": {
        "enabled": True,
        "minimum_tempo_lambda": 0.75,
        "minimum_resolved_events": 8,
        "max_count": 4,
        "max_rate": 0.20,
        "consecutive_event_limit": 3,
        "terminate_on_rate": False,
    },
    "joint_limits": {
        "diagnostic_fraction": 0.90,
        "soft_penalty_start_fraction": 0.95,
        "soft_penalty_weight": 0.01,
    },
    "reward": {
        "grip_weight": {
            "A0_PICK_GRIP": 1.00,
            "A1_TIP_READY": 0.10,
            "A2_SINGLE_CROSSING": 0.02,
            "A3_TIMED_SINGLE": 0.02,
            "A4_STRUM_CONTEXT_RECOVERY": 0.02,
            "S0_TWO_STRING_STRUM": 0.02,
            "S1_STRUM_SPAN": 0.02,
            "S2_TIMED_STRUM": 0.02,
            "S3_SONG_INTEGRATION": 0.02,
        },
        "reach_weight": 0.20,
        "reach_discount": 0.95,
        "approach_progress_weight": {
            "A0_PICK_GRIP": 0.00,
            "A1_TIP_READY": 0.00,
            "A2_SINGLE_CROSSING": 0.10,
            "A3_TIMED_SINGLE": 0.10,
            "A4_STRUM_CONTEXT_RECOVERY": 0.10,
            "S0_TWO_STRING_STRUM": 0.25,
            "S1_STRUM_SPAN": 0.30,
            "S2_TIMED_STRUM": 0.30,
            "S3_SONG_INTEGRATION": 0.20,
        },
        "ready_quality_weight": {
            "A0_PICK_GRIP": 0.00,
            "A1_TIP_READY": 0.75,
            "A2_SINGLE_CROSSING": 0.05,
            "A3_TIMED_SINGLE": 0.03,
            "A4_STRUM_CONTEXT_RECOVERY": 0.03,
            "S0_TWO_STRING_STRUM": 0.03,
            "S1_STRUM_SPAN": 0.02,
            "S2_TIMED_STRUM": 0.02,
            "S3_SONG_INTEGRATION": 0.02,
        },
        "crossing_reward": 1.00,
        "timing_progress_reward": {
            "A0_PICK_GRIP": 0.00,
            "A1_TIP_READY": 0.00,
            "A2_SINGLE_CROSSING": 0.00,
            "A3_TIMED_SINGLE": 1.00,
            "A4_STRUM_CONTEXT_RECOVERY": 0.00,
            "S0_TWO_STRING_STRUM": 0.00,
            "S1_STRUM_SPAN": 0.00,
            "S2_TIMED_STRUM": 2.00,
            "S3_SONG_INTEGRATION": 0.75,
        },
        "timing_wait_reward": {
            "A0_PICK_GRIP": 0.00,
            "A1_TIP_READY": 0.00,
            "A2_SINGLE_CROSSING": 0.00,
            "A3_TIMED_SINGLE": 0.008,
            "A4_STRUM_CONTEXT_RECOVERY": 0.00,
            "S0_TWO_STRING_STRUM": 0.00,
            "S1_STRUM_SPAN": 0.00,
            "S2_TIMED_STRUM": 0.010,
            "S3_SONG_INTEGRATION": 0.010,
        },
        "early_timing_penalty": {
            "A0_PICK_GRIP": 0.00,
            "A1_TIP_READY": 0.00,
            "A2_SINGLE_CROSSING": 0.00,
            "A3_TIMED_SINGLE": 0.50,
            "A4_STRUM_CONTEXT_RECOVERY": 0.00,
            "S0_TWO_STRING_STRUM": 0.00,
            "S1_STRUM_SPAN": 0.00,
            "S2_TIMED_STRUM": 1.00,
            "S3_SONG_INTEGRATION": 1.00,
        },
        "strum_progress_reward": {
            "A0_PICK_GRIP": 0.00,
            "A1_TIP_READY": 0.00,
            "A2_SINGLE_CROSSING": 0.00,
            "A3_TIMED_SINGLE": 0.00,
            "A4_STRUM_CONTEXT_RECOVERY": 0.25,
            "S0_TWO_STRING_STRUM": 0.75,
            "S1_STRUM_SPAN": 1.00,
            "S2_TIMED_STRUM": 1.00,
            "S3_SONG_INTEGRATION": 1.00,
        },
        "strum_terminal_progress_reward": {
            "A0_PICK_GRIP": 0.00,
            "A1_TIP_READY": 0.00,
            "A2_SINGLE_CROSSING": 0.00,
            "A3_TIMED_SINGLE": 0.00,
            "A4_STRUM_CONTEXT_RECOVERY": 0.25,
            "S0_TWO_STRING_STRUM": 0.75,
            "S1_STRUM_SPAN": 1.00,
            "S2_TIMED_STRUM": 1.00,
            "S3_SONG_INTEGRATION": 0.75,
        },
        "strum_physical_completion_reward": {
            "A0_PICK_GRIP": 0.00,
            "A1_TIP_READY": 0.00,
            "A2_SINGLE_CROSSING": 0.00,
            "A3_TIMED_SINGLE": 0.00,
            "A4_STRUM_CONTEXT_RECOVERY": 0.35,
            "S0_TWO_STRING_STRUM": 0.50,
            "S1_STRUM_SPAN": 0.50,
            "S2_TIMED_STRUM": 0.50,
            "S3_SONG_INTEGRATION": 0.40,
        },
        "strum_microtiming_weight": {
            "A0_PICK_GRIP": 0.00,
            "A1_TIP_READY": 0.00,
            "A2_SINGLE_CROSSING": 0.00,
            "A3_TIMED_SINGLE": 0.00,
            "A4_STRUM_CONTEXT_RECOVERY": 0.00,
            "S0_TWO_STRING_STRUM": 0.00,
            "S1_STRUM_SPAN": 0.00,
            "S2_TIMED_STRUM": 0.25,
            "S3_SONG_INTEGRATION": 0.25,
        },
        "strum_duration_core_ms": 15.0,
        "completion_reward": {
            "A0_PICK_GRIP": 0.00,
            "A1_TIP_READY": 0.15,
            "A2_SINGLE_CROSSING": 0.50,
            "A3_TIMED_SINGLE": 0.35,
            "A4_STRUM_CONTEXT_RECOVERY": 0.35,
            "S0_TWO_STRING_STRUM": 0.35,
            "S1_STRUM_SPAN": 0.30,
            "S2_TIMED_STRUM": 0.25,
            "S3_SONG_INTEGRATION": 0.25,
        },
        "wrong_crossing_penalty": {
            "A0_PICK_GRIP": 0.00,
            "A1_TIP_READY": 0.35,
            "A2_SINGLE_CROSSING": 0.35,
            "A3_TIMED_SINGLE": 0.35,
            "A4_STRUM_CONTEXT_RECOVERY": 0.75,
            "S0_TWO_STRING_STRUM": 0.50,
            "S1_STRUM_SPAN": 0.40,
            "S2_TIMED_STRUM": 0.30,
            "S3_SONG_INTEGRATION": 0.35,
        },
        "unprepared_crossing_penalty": {
            "A0_PICK_GRIP": 0.00,
            "A1_TIP_READY": 0.00,
            "A2_SINGLE_CROSSING": 1.00,
            "A3_TIMED_SINGLE": 1.00,
            "A4_STRUM_CONTEXT_RECOVERY": 1.00,
            "S0_TWO_STRING_STRUM": 0.75,
            "S1_STRUM_SPAN": 0.75,
            "S2_TIMED_STRUM": 0.75,
            "S3_SONG_INTEGRATION": 1.00,
        },
        "miss_penalty": {
            "A0_PICK_GRIP": 0.00,
            "A1_TIP_READY": 0.50,
            "A2_SINGLE_CROSSING": 0.50,
            "A3_TIMED_SINGLE": 0.50,
            "A4_STRUM_CONTEXT_RECOVERY": 0.50,
            "S0_TWO_STRING_STRUM": 0.40,
            "S1_STRUM_SPAN": 0.40,
            "S2_TIMED_STRUM": 0.40,
            "S3_SONG_INTEGRATION": 1.50,
        },
        "premature_release_penalty": {
            "A0_PICK_GRIP": 0.00,
            "A1_TIP_READY": 0.00,
            "A2_SINGLE_CROSSING": 0.00,
            "A3_TIMED_SINGLE": 0.75,
            "A4_STRUM_CONTEXT_RECOVERY": 0.00,
            "S0_TWO_STRING_STRUM": 0.00,
            "S1_STRUM_SPAN": 0.00,
            "S2_TIMED_STRUM": 1.00,
            "S3_SONG_INTEGRATION": 1.00,
        },
        "zone_weight": 0.20,
        "timing_core_ms": 20.0,
        "recovery_progress_reward": {
            "A0_PICK_GRIP": 0.00,
            "A1_TIP_READY": 0.00,
            "A2_SINGLE_CROSSING": 0.10,
            "A3_TIMED_SINGLE": 0.10,
            "A4_STRUM_CONTEXT_RECOVERY": 0.75,
            "S0_TWO_STRING_STRUM": 0.60,
            "S1_STRUM_SPAN": 0.50,
            "S2_TIMED_STRUM": 0.40,
            "S3_SONG_INTEGRATION": 0.30,
        },
        "recovery_completion_reward": {
            "A0_PICK_GRIP": 0.00,
            "A1_TIP_READY": 0.00,
            "A2_SINGLE_CROSSING": 0.10,
            "A3_TIMED_SINGLE": 0.10,
            "A4_STRUM_CONTEXT_RECOVERY": 0.75,
            "S0_TWO_STRING_STRUM": 0.60,
            "S1_STRUM_SPAN": 0.50,
            "S2_TIMED_STRUM": 0.40,
            "S3_SONG_INTEGRATION": 0.30,
        },
        "recovery_speed_penalty_weight": {
            "A0_PICK_GRIP": 0.00,
            "A1_TIP_READY": 0.00,
            "A2_SINGLE_CROSSING": 0.00,
            "A3_TIMED_SINGLE": 0.00,
            "A4_STRUM_CONTEXT_RECOVERY": 0.25,
            "S0_TWO_STRING_STRUM": 0.20,
            "S1_STRUM_SPAN": 0.15,
            "S2_TIMED_STRUM": 0.10,
            "S3_SONG_INTEGRATION": 0.10,
        },
        "recovery_speed_limit_m_s": 0.20,
        "recovery_speed_excess_m_s": 0.50,
    },
    "episode": {
        "A0_PICK_GRIP": 120,
        "A1_TIP_READY": 180,
        "A2_SINGLE_CROSSING": 240,
        "A3_TIMED_SINGLE": 240,
        "A4_STRUM_CONTEXT_RECOVERY": 300,
        "S0_TWO_STRING_STRUM": 300,
        "S1_STRUM_SPAN": 360,
        "S2_TIMED_STRUM": 300,
        "S3_SONG_INTEGRATION": 600,
        "song_events_per_episode": 8,
        "timed_lead_frames": 30,
    },
    "curriculum": {
        "min_iterations": {
            "A0_PICK_GRIP": 50,
            "A1_TIP_READY": 100,
            "A2_SINGLE_CROSSING": 150,
            "A3_TIMED_SINGLE": 200,
            "A4_STRUM_CONTEXT_RECOVERY": 120,
            "S0_TWO_STRING_STRUM": 250,
            "S1_STRUM_SPAN": 250,
            "S2_TIMED_STRUM": 300,
            "S3_SONG_INTEGRATION": 300,
        },
        "max_iterations": {
            "A0_PICK_GRIP": 500,
            "A1_TIP_READY": 1000,
            "A2_SINGLE_CROSSING": 1500,
            "A3_TIMED_SINGLE": 2500,
            "A4_STRUM_CONTEXT_RECOVERY": 1200,
            "S0_TWO_STRING_STRUM": 2500,
            "S1_STRUM_SPAN": 3000,
            "S2_TIMED_STRUM": 3500,
            "S3_SONG_INTEGRATION": 6000,
        },
        "promotion_windows": 3,
        "terminal_evidence_fraction": 1.0,
        "timing_tolerances_ms": (100, 67, 50),
        "s2_profiles": (
            {
                "name": "E0_BALANCED_ENDPOINT", "tolerance_ms": 400,
                "approach_lead_s": 0.25,
                "timing_early_grace_ms": 180.0,
                "timing_early_penalty_scale_ms": 220.0,
                "timing_pass_rate": 0.50, "completion_rate": 0.80,
                "worst_direction_completion_rate": 0.75,
                "end_to_end_recovery_rate": 0.75,
                "timing_rms_ms": 300.0, "duration_mae_ms": 200.0,
                "timing_center_mean_abs_ms": 300.0,
                "timing_center_tail_abs_ms": 380.0,
                "timing_reward_core_ms": 300.0,
                "duration_reward_core_ms": 250.0,
                "zone_active": False, "zone_success_rate": 0.0,
            },
            {
                "name": "T0_400MS", "tolerance_ms": 400,
                "approach_lead_s": 0.25,
                "timing_early_grace_ms": 180.0,
                "timing_early_penalty_scale_ms": 220.0,
                "timing_pass_rate": 0.70, "completion_rate": 0.70,
                "worst_direction_completion_rate": 0.70,
                "end_to_end_recovery_rate": 0.70,
                "timing_rms_ms": 300.0, "duration_mae_ms": 200.0,
                "timing_center_mean_abs_ms": 180.0,
                "timing_center_tail_abs_ms": 300.0,
                "timing_reward_core_ms": 300.0,
                "duration_reward_core_ms": 250.0,
                "zone_active": False, "zone_success_rate": 0.0,
            },
            {
                "name": "T1_250MS", "tolerance_ms": 250,
                "approach_lead_s": 0.14,
                "timing_early_grace_ms": 75.0,
                "timing_early_penalty_scale_ms": 150.0,
                "timing_pass_rate": 0.75, "completion_rate": 0.75,
                "worst_direction_completion_rate": 0.75,
                "end_to_end_recovery_rate": 0.75,
                "timing_rms_ms": 200.0, "duration_mae_ms": 150.0,
                "timing_center_mean_abs_ms": 110.0,
                "timing_center_tail_abs_ms": 190.0,
                "timing_reward_core_ms": 180.0,
                "duration_reward_core_ms": 180.0,
                "zone_active": False, "zone_success_rate": 0.0,
            },
            {
                "name": "T2_225MS", "tolerance_ms": 225,
                "approach_lead_s": 0.13,
                "timing_early_grace_ms": 60.0,
                "timing_early_penalty_scale_ms": 130.0,
                "timing_pass_rate": 0.78, "completion_rate": 0.78,
                "worst_direction_completion_rate": 0.78,
                "end_to_end_recovery_rate": 0.78,
                "timing_rms_ms": 180.0, "duration_mae_ms": 140.0,
                "timing_center_mean_abs_ms": 95.0,
                "timing_center_tail_abs_ms": 170.0,
                "timing_reward_core_ms": 160.0,
                "duration_reward_core_ms": 165.0,
                "zone_active": False, "zone_success_rate": 0.0,
            },
            {
                "name": "T3_200MS", "tolerance_ms": 200,
                "approach_lead_s": 0.12,
                "timing_early_grace_ms": 50.0,
                "timing_early_penalty_scale_ms": 115.0,
                "timing_pass_rate": 0.80, "completion_rate": 0.80,
                "worst_direction_completion_rate": 0.80,
                "end_to_end_recovery_rate": 0.80,
                "timing_rms_ms": 165.0, "duration_mae_ms": 130.0,
                "timing_center_mean_abs_ms": 80.0,
                "timing_center_tail_abs_ms": 150.0,
                "timing_reward_core_ms": 145.0,
                "duration_reward_core_ms": 150.0,
                "zone_active": False, "zone_success_rate": 0.0,
            },
            {
                "name": "T4_175MS", "tolerance_ms": 175,
                "approach_lead_s": 0.11,
                "timing_early_grace_ms": 40.0,
                "timing_early_penalty_scale_ms": 100.0,
                "timing_pass_rate": 0.82, "completion_rate": 0.82,
                "worst_direction_completion_rate": 0.82,
                "end_to_end_recovery_rate": 0.82,
                "timing_rms_ms": 145.0, "duration_mae_ms": 115.0,
                "timing_center_mean_abs_ms": 70.0,
                "timing_center_tail_abs_ms": 130.0,
                "timing_reward_core_ms": 125.0,
                "duration_reward_core_ms": 135.0,
                "zone_active": False, "zone_success_rate": 0.0,
            },
            {
                "name": "T5_150MS", "tolerance_ms": 150,
                "approach_lead_s": 0.10,
                "timing_early_grace_ms": 30.0,
                "timing_early_penalty_scale_ms": 85.0,
                "timing_pass_rate": 0.85, "completion_rate": 0.85,
                "worst_direction_completion_rate": 0.85,
                "end_to_end_recovery_rate": 0.85,
                "timing_rms_ms": 120.0, "duration_mae_ms": 100.0,
                "timing_center_mean_abs_ms": 55.0,
                "timing_center_tail_abs_ms": 110.0,
                "timing_reward_core_ms": 100.0,
                "duration_reward_core_ms": 120.0,
                "zone_active": False, "zone_success_rate": 0.0,
            },
            {
                "name": "T6_100MS", "tolerance_ms": 100,
                "approach_lead_s": 0.09,
                "timing_early_grace_ms": 20.0,
                "timing_early_penalty_scale_ms": 60.0,
                "timing_pass_rate": 0.88, "completion_rate": 0.88,
                "worst_direction_completion_rate": 0.88,
                "end_to_end_recovery_rate": 0.88,
                "timing_rms_ms": 80.0, "duration_mae_ms": 70.0,
                "timing_center_mean_abs_ms": 35.0,
                "timing_center_tail_abs_ms": 75.0,
                "timing_reward_core_ms": 60.0,
                "duration_reward_core_ms": 80.0,
                "zone_active": False, "zone_success_rate": 0.0,
            },
            {
                "name": "Z0_100MS", "tolerance_ms": 100,
                "approach_lead_s": 0.09,
                "timing_early_grace_ms": 20.0,
                "timing_early_penalty_scale_ms": 60.0,
                "timing_pass_rate": 0.88, "completion_rate": 0.88,
                "worst_direction_completion_rate": 0.88,
                "end_to_end_recovery_rate": 0.88,
                "timing_rms_ms": 80.0, "duration_mae_ms": 70.0,
                "timing_center_mean_abs_ms": 35.0,
                "timing_center_tail_abs_ms": 75.0,
                "timing_reward_core_ms": 60.0,
                "duration_reward_core_ms": 80.0,
                "zone_active": True, "zone_success_rate": 0.80,
            },
            {
                "name": "Z1_67MS", "tolerance_ms": 67,
                "approach_lead_s": 0.08,
                "timing_early_grace_ms": 12.0,
                "timing_early_penalty_scale_ms": 40.0,
                "timing_pass_rate": 0.90, "completion_rate": 0.90,
                "worst_direction_completion_rate": 0.90,
                "end_to_end_recovery_rate": 0.90,
                "timing_rms_ms": 50.0, "duration_mae_ms": 45.0,
                "timing_center_mean_abs_ms": 25.0,
                "timing_center_tail_abs_ms": 50.0,
                "timing_reward_core_ms": 35.0,
                "duration_reward_core_ms": 45.0,
                "zone_active": True, "zone_success_rate": 0.90,
            },
            {
                "name": "Z2_50MS", "tolerance_ms": 50,
                "approach_lead_s": 0.07,
                "timing_early_grace_ms": 8.0,
                "timing_early_penalty_scale_ms": 30.0,
                "timing_pass_rate": 0.95, "completion_rate": 0.90,
                "worst_direction_completion_rate": 0.90,
                "end_to_end_recovery_rate": 0.90,
                "timing_rms_ms": 35.0, "duration_mae_ms": 30.0,
                "timing_center_mean_abs_ms": 18.0,
                "timing_center_tail_abs_ms": 35.0,
                "timing_reward_core_ms": 20.0,
                "duration_reward_core_ms": 25.0,
                "zone_active": True, "zone_success_rate": 0.95,
            },
        ),
        "s2_rollback_windows": 3,
        "s2_rollback_cooldown_iterations": 200,
        "s2_profile_adaptation_iterations": 200,
        "s2_rollback_timing_pass_rate": 0.35,
        "s2_rollback_completion_rate": 0.25,
        "s2_rollback_traversal_rate": 0.80,
        "s2_rollback_direction_rate": 0.80,
        "s2_rollback_false_positive_rate": 0.20,
        "s2_endpoint_recovery_windows": 3,
        "s2_endpoint_recovery_trigger_rate": 0.60,
        "s2_endpoint_focus_fraction": 0.70,
        "s2_endpoint_proximal_std_floor": 0.030,
        "s2_endpoint_std_floor_profiles": (
            "E0_BALANCED_ENDPOINT", "T0_400MS"),
        "tempo_lambdas": (
            0.0, 0.25, 0.5, 0.75, 0.9, 0.95, 0.975, 1.0),
        # Increase temporal credit assignment before original-tempo training.
        # A count larger than the selected song is clamped to its event count.
        "s3_episode_event_counts": (8, 16, 32, 42, 42, 42, 42, 42),
        "s3_tempo_gates": (
            {"f1": 0.96, "wrong_termination_rate": 0.00,
             "blocked_crossing_rate": 0.020},
            {"f1": 0.96, "wrong_termination_rate": 0.00,
             "blocked_crossing_rate": 0.020},
            {"f1": 0.97, "wrong_termination_rate": 0.00,
             "blocked_crossing_rate": 0.020},
            {"f1": 0.975, "wrong_termination_rate": 0.08,
             "blocked_crossing_rate": 0.025},
            {"f1": 0.98, "wrong_termination_rate": 0.05,
             "blocked_crossing_rate": 0.020},
            {"f1": 0.985, "wrong_termination_rate": 0.03,
             "blocked_crossing_rate": 0.015},
            {"f1": 0.987, "wrong_termination_rate": 0.02,
             "blocked_crossing_rate": 0.012},
            {"f1": 0.99, "wrong_termination_rate": 0.01,
             "blocked_crossing_rate": 0.010},
        ),
        # Once failure evidence exists, rehearse difficult contiguous windows
        # in half of the environments and retain a uniform 50% holdout.  This
        # is automatic; the CLI does not expose a sampling-fraction knob.
        "stalled_hard_sample_fraction": 0.50,
        "stalled_hard_rehearsal_events": 4,
        "stalled_failure_score_decay": 0.995,
        "stalled_failure_prior_exposure": 16.0,
        "stalled_hard_window_probability_cap": 0.10,
        # Direction-specific failures are already represented by the
        # exposure-normalized event score.  A second sampler would reduce the
        # uniform holdout below 50% and is therefore disabled by default.
        "s3_upstroke_sample_fraction": 0.00,
        "s3_upstroke_window_probability_cap": 0.10,
        "s3_uniform_curriculum_evidence_only": True,
        # When S3 remains stalled at a relaxed tempo, switch to a full-song
        # original-tempo rehearsal instead of repeating the same short-window
        # distribution indefinitely.
        "s3_stalled_original_tempo_recovery": True,
        "s3_original_tempo_retention_drop_f1": 0.05,
        "s3_original_tempo_holdout_max_age_iterations": 1500,
        "strum_spans": (3, 4, 5, 6),
        "grip_success_rate": 0.90,
        "grip_quality_mean": 0.92,
        "grip_quality_p05": 0.85,
        "pinch_quality_mean": 0.95,
        "free_quality_mean": 0.85,
        "max_grip_bad_frame_rate": 0.05,
        "max_grip_bad_streak_frames": 12,
        "ready_success_rate": 0.85,
        "release_recall": 0.80,
        "max_wrong_rate_by_stage": {
            "A0_PICK_GRIP": 1.00,
            "A1_TIP_READY": 1.00,
            "A2_SINGLE_CROSSING": 0.05,
            "A3_TIMED_SINGLE": 0.05,
            "A4_STRUM_CONTEXT_RECOVERY": 0.05,
            "S0_TWO_STRING_STRUM": 0.08,
            "S1_STRUM_SPAN": 0.07,
            "S2_TIMED_STRUM": 0.05,
            "S3_SONG_INTEGRATION": 0.05,
        },
        "max_failure_rate_by_stage": {
            "A0_PICK_GRIP": 0.00,
            "A1_TIP_READY": 0.00,
            "A2_SINGLE_CROSSING": 0.00,
            "A3_TIMED_SINGLE": 0.00,
            "A4_STRUM_CONTEXT_RECOVERY": 0.05,
            "S0_TWO_STRING_STRUM": 0.05,
            "S1_STRUM_SPAN": 0.03,
            "S2_TIMED_STRUM": 0.02,
            "S3_SONG_INTEGRATION": 0.00,
        },
        "timed_f1_by_level": (0.80, 0.90, 0.95),
        "zone_f1": 0.98,
        "zone_success_rate": 0.95,
        "strum_completion_rate": 0.90,
        "strum_traversal_recall": 0.95,
        "strum_order_accuracy": 0.98,
        "strum_direction_accuracy_by_stage": {
            "A0_PICK_GRIP": 0.00,
            "A1_TIP_READY": 0.00,
            "A2_SINGLE_CROSSING": 0.00,
            "A3_TIMED_SINGLE": 0.00,
            "A4_STRUM_CONTEXT_RECOVERY": 0.95,
            "S0_TWO_STRING_STRUM": 0.95,
            "S1_STRUM_SPAN": 0.97,
            "S2_TIMED_STRUM": 0.98,
            "S3_SONG_INTEGRATION": 0.98,
        },
        "recovery_completion_rate": 0.95,
        "full_recovery_completion_rate": 0.95,
        "handoff_recovery_completion_rate": 0.95,
        "max_recovery_reset_rate_by_stage": {
            "A0_PICK_GRIP": 1.00,
            "A1_TIP_READY": 1.00,
            "A2_SINGLE_CROSSING": 0.02,
            "A3_TIMED_SINGLE": 0.02,
            "A4_STRUM_CONTEXT_RECOVERY": 0.05,
            "S0_TWO_STRING_STRUM": 0.08,
            "S1_STRUM_SPAN": 0.06,
            "S2_TIMED_STRUM": 0.04,
            "S3_SONG_INTEGRATION": 0.02,
        },
        "max_blocked_crossing_rate_by_stage": {
            "A0_PICK_GRIP": 1.00,
            "A1_TIP_READY": 1.00,
            "A2_SINGLE_CROSSING": 0.02,
            "A3_TIMED_SINGLE": 0.02,
            "A4_STRUM_CONTEXT_RECOVERY": 0.05,
            "S0_TWO_STRING_STRUM": 0.08,
            "S1_STRUM_SPAN": 0.06,
            "S2_TIMED_STRUM": 0.04,
            "S3_SONG_INTEGRATION": 0.02,
        },
        "strum_timing_rms_ms": 35.0,
        "strum_sweep_duration_mae_ms": 30.0,
    },
    "evaluation": {
        "full_song_interval_iterations": 500,
        "full_song_episodes": 64,
        "grip_quality_mean": 0.92,
        "grip_quality_p05": 0.85,
        "pinch_quality_mean": 0.95,
        "free_quality_mean": 0.85,
        "max_grip_bad_frame_rate": 0.05,
        "max_grip_bad_streak_frames": 12,
        "f1": 0.99,
        "precision": 0.99,
        "recall": 0.99,
        "max_wrong_rate": 0.01,
        "timing_p95_ms": 50.0,
        "zone_success_rate": 0.99,
        "strum_completion_rate": 0.95,
        "strum_traversal_recall": 0.99,
        "strum_order_accuracy": 0.99,
        "strum_direction_accuracy": 0.99,
        "strum_max_unplanned_rate": 0.01,
        "recovery_completion_rate": 1.0,
        "full_recovery_completion_rate": 1.0,
        "handoff_recovery_completion_rate": 1.0,
        "max_recovery_reset_count": 0.0,
        "max_blocked_crossing_count": 0.0,
        "strum_timing_rms_ms": 25.0,
        "strum_sweep_duration_mae_ms": 20.0,
    },
    "ppo": {
        "horizon": 32,
        "epochs": 5,
        "minibatch_size": 2048,
        "gamma": 0.95,
        "gae_lambda": 0.95,
        "clip_ratio": 0.2,
        "value_coef": 1.0,
        "entropy_coef": 0.001,
        "actor_learning_rate": 3e-6,
        "learning_rate": 3e-4,
        "completed_strike_lr_multiplier": 1.0,
        "max_grad_norm": 1.0,
        "target_kl": 0.03,
        "action_saturation_regularization_weight": 0.002,
        "action_saturation_regularization_threshold": 0.90,
        "save_interval": 500,
        "log_interval": 1,
    },
    "periodic_video": {
        "minimum_checkpoint_gap_iterations": 1900,
        "fps": 30,
        "width": 1600,
        "height": 900,
    },
    "artifact_max_steps": 900,
    "resource_guard": {
        "max_num_envs": 1024,
        "min_free_vram_gib": 8.0,
        "min_available_ram_gib": 8.0,
        "min_free_disk_gib": 10.0,
    },
}
