HUMANOID_COLLISION_FILTER = 1
GUITAR_COLLISION_FILTER = 2
DISABLED_COLLISION_FILTER = (
    HUMANOID_COLLISION_FILTER | GUITAR_COLLISION_FILTER)

THUMB_PAD_BODY = "LH:thumb_pad"
THUMB_SUPPORT_PROXY_BODY = "G:thumb_support_proxy"
SHAPE_CONTACT_OFFSET = 0.0001
